# Site settings
title: Timothy's Blog 
email: timothy-blog@zts1993.com
description: > # this means to ignore newlines until "baseurl:"
  I am good at installation and uninstallation Ai, Fw, Fl, Br, Ae, Pr, Id, Ps and other software , proficient in CSS, JavaScript, PHP, ASP, C, C ++, C #, Java, Ruby, Perl, Lisp, python, Objective -C, ActionScript, Pascal, spss, sas, ruby ​​and other spelling familiar with Windows, Linux, Mac, Android, IOS, WP8 switch machine systems
baseurl: "" # the subpath of your site, e.g. /blog
url: http://b.zts1993.com
rss_url: /pages/atom.xml
timezone: Asia/Shanghai
author : "Timothy Zhang"
email : "blog@zts1993.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html

kramdown:
  input: GFM

# Outputting
permalink: date
paginate_path: /page:num
timezone: Asia/Shanghai


disqus:
  shortname: timothyzhangblog


baidu:
  id: 8a742c8021b1298467ba1c76ffc40743


avatar: http://en.gravatar.com/userimage/34915036/8f2c452d5b8a8e26578a9dd1445fbfd0?size=200
favicon: http://en.gravatar.com/userimage/34915036/8f2c452d5b8a8e26578a9dd1445fbfd0?size=200