# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Timothy's Blog 
email: timothy-blog@zts1993.com
description: > # this means to ignore newlines until "baseurl:"
  I am good at installation and uninstallation Ai, Fw, Fl, Br, Ae, Pr, Id, Ps and other software , proficient in CSS, JavaScript, PHP, ASP, C, C ++, C #, Java, Ruby, Perl, Lisp, python, Objective -C, ActionScript, Pascal, spss, sas, ruby ​​and other spelling familiar with Windows, Linux, Mac, Android, IOS, WP8 switch machine systems
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.zts1993.com" # the base hostname & protocol for your site
twitter_username: zts1993
github_username:  zts1993

timezone: Asia/Shanghai

# Build settings
markdown: kramdown
highlighter: rouge

# Outputting
permalink: date
paginate_path: /page:num
timezone: Asia/Shanghai
